name: turistando
description: Projeto conceito de arquitetura.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # App
  flutter_mobx: ^2.0.6+5

  #Domain
  mobx: ^2.2.0
  local_auth: ^2.1.7
  flutter_modular: ^5.0.3


  # Data
  dio: ^5.3.2
  dartz: ^0.10.1
  objectbox: ^2.2.1
  path_provider: ^2.1.1
  objectbox_flutter_libs: ^2.2.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
