name: turistando
description: Projeto conceito de arquitetura.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.8

  # logic
  result_dart: 1.1.1
  flutter_modular: ^6.3.4

  # data
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
